name: push-cql

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Cut Image Workflow
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: darena-solutions/meldrx-ecosystem
          event-type: updated-cql-main
